pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-generic-virus-scanner
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
    when:
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - SCANNER_PVC_SIZE=1Gi
      - NATS_CPU_REQUEST=1
      - NATS_CPU_LIMIT=1.5
      - NATS_RAM_REQUEST=1Gi
      - NATS_RAM_LIMIT=1.5Gi
      - CLAMAV_CPU_REQUEST=1
      - CLAMAV_CPU_LIMIT=1.5
      - CLAMAV_RAM_REQUEST=1Gi
      - CLAMAV_RAM_LIMIT=1.5Gi
    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - export S3_BUCKET_NAME=$$NOTPROD_S3_BUCKET_NAME
      - export S3_KEY_PREFIX=$$NOTPROD_S3_KEY_PREFIX
      - export S3_ACCESS_KEY_ID=$$NOTPROD_S3_ACCESS_KEY_ID
      - export S3_SECRET_ACCESS_KEY=$$NOTPROD_S3_SECRET_ACCESS_KEY
      - export INPUT_DIR=$$INPUT_DIR
      - export OUTPUT_DIR=$$OUTPUT_DIR
      - export QUARANTINE_DIR=$$QUARANTINE_DIR
      - kd -f kube/pvc.yml -f kube/deployment.yml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
      - NOTPROD_S3_BUCKET_NAME
      - NOTPROD_S3_KEY_PREFIX
      - NOTPROD_S3_ACCESS_KEY_ID
      - NOTPROD_S3_SECRET_ACCESS_KEY
      - INPUT_DIR
      - OUTPUT_DIR
      - QUARANTINE_DIR
    when:
      event: push